# XXX consider using alpine and apk add'ing curl?
image: node:20

variables:
  PACKAGE_NAME: "investigator"
  MANIFEST_NAME: "system.json"
  MANIFEST_PATH: "public/${MANIFEST_NAME}"
  ZIP_FILE_NAME: "${PACKAGE_NAME}.zip"
  PACKAGE_BASE: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}"
  PACKAGE_LATEST_BASE: "${PACKAGE_BASE}/latest"
  PACKAGE_VERSION_BASE: "${PACKAGE_BASE}/${CI_COMMIT_TAG}"
  PACKAGE_LATEST_MANIFEST: "${PACKAGE_LATEST_BASE}/${MANIFEST_NAME}"
  PACKAGE_LATEST_DOWNLOAD: "${PACKAGE_LATEST_BASE}/${ZIP_FILE_NAME}"
  PACKAGE_VERSION_MANIFEST: "${PACKAGE_VERSION_BASE}/${MANIFEST_NAME}"
  PACKAGE_VERSION_DOWNLOAD: "${PACKAGE_VERSION_BASE}/${ZIP_FILE_NAME}"

stages:
  - build
  - upload
  - release

cache:
  paths:
    - node_modules/


build:
  stage: build
  script:
    - pwd
    - ls -l
    - cat tsconfig.json
    - npx tsc --version
    - export
    - corepack enable
    - pnpm --version
    - pnpm i
    - if [[ -n $CI_COMMIT_TAG ]]; then ./tasks.js updateManifestFromCITagPush; fi
    - pnpm package
    - ls -l
    - ls -l package
  artifacts:
    expire_in: 1 week
    paths:
      - package
      - $MANIFEST_PATH

upload-version:
  stage: upload
  image: curlimages/curl:latest
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${MANIFEST_PATH} "${PACKAGE_VERSION_MANIFEST}"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file package/${ZIP_FILE_NAME} "${PACKAGE_VERSION_DOWNLOAD}"'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'

upload-latest:
  stage: upload
  image: curlimages/curl:latest
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${MANIFEST_PATH} "${PACKAGE_LATEST_MANIFEST}"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file package/${ZIP_FILE_NAME} "${PACKAGE_LATEST_DOWNLOAD}"'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/ && $CI_COMMIT_TAG !~ /-(alpha|beta|test|dev|try)/'


release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'Creating release'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/'
  release:
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    description: '**Installation:** To manually install this release, please use the following manifest URL: ${PACKAGE_VERSION_MANIFEST}'
    assets:
      links:
        # links the release to the system manifest from this CI workflow
        - name: ${MANIFEST_NAME}
          url: ${PACKAGE_VERSION_MANIFEST}
        # links the release to the zip file from this CI workflow
        - name: '$ZIP_FILE_NAME'
          url: ${PACKAGE_VERSION_DOWNLOAD}
